services:
  dashlet:
    build: .
    image: ghcr.io/jaberio/dashlet:latest
    container_name: dashlet
    ports:
      - "8989:8989"
    volumes:
      # Mount the 'public' directory. Docker will populate it if empty.
      - ./app/public:/app/public
    restart: unless-stopped
