services:
  dashlet:
    image: jaypel/dashlet:latest
    container_name: dashlet
    ports:
      - "3000:3000"
    volumes:
      # Mount the 'user' directory. Docker will populate it if empty.
      - ./app/user:/app/user
    restart: unless-stopped
