services:
  dashlet:
    image: jaypel/dashlet:latest
    container_name: dashlet
    ports:
      - "3000:3000"
    volumes:
      # Mount the 'public' directory. Docker will populate it if empty.
      - ./app/public:/app/public
    restart: unless-stopped
